name: "Run"

on:
  release:
    types:
      - "published"

jobs:
  AnotherOne:
    outputs:
      version: ${{ steps.dont.outputs.version }}
    runs-on: ubuntu-20.04
    steps:
      - name: Run
        run: |
          echo this will run
          echo "::set-output name=version::4.1.8"
  DONOT:
    if: true
    outputs:
      version: ${{ steps.dont.outputs.version }}
    runs-on: ubuntu-20.04
    steps:
      - name: Don't run
        run: |
          echo this will not run
          echo "::set-output name=version::4.1.8"
          exit 1
  Do:
    needs: [DONOT, AnotherOne]
    runs-on: ubuntu-latest
    steps:
      - name: show vars
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          
          LATEST_RELEASE="$(
            git -c 'versionsort.suffix=-' ls-remote -t --exit-code --refs --sort=-v:refname "https://github.com/$GITHUB_REPOSITORY" '*' |
              sed -En '1!q;s/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/gp'
          )"

          echo "LATEST_RELEASE: $LATEST_RELEASE"

          echo "FROM_NEEDS: ${{ needs.DONOT.outputs.version }}"

      - name: jq?
        run: which jq || true
